[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "valysis"
version = "1.1.1"
description = "A platform/hardware agnostic Value Set Analysis (VSA) library for Reverse Engineering tools."
readme = "README.md"
requires-python = ">=3.9"
license = { file = "LICENSE" }
authors = [
  { name = "nulsie", email = "donotmailme@mail.com" }
]
dependencies = []
classifiers = [
    "Programming Language :: Python :: 3",
    "Topic :: Security",
    "Topic :: Software Development :: Disassemblers",
]

[project.urls]
Homepage = "https://codeberg.org/nulsie/valysis"
"Codeberg" = "https://codeberg.org/nulsie/valysis"
"GitHub" = "https://github.com/nulsie/valysis"
